"""SILO-BENCH compatible agent that satisfies the BaseAgent protocol.

SiloBenchAgent speaks SILO-BENCH's XML tool-call language and routes
network operations through the Simulator's Network layer, reproducing
the original benchmark behaviour without touching engine.py.

Tool semantics
--------------
Non-network tools (resolved inline during decide()):
  receive_messages  → returns current _inbox (populated by observe())
  list_agents       → returns all agent IDs [0 .. num_agents-1]
  wait              → terminal; ends the turn, no messages sent

Network tools (converted to SimMessage, delivered next round):
  send_message      → SimMessage to a specific recipient (msg protocol)
  broadcast_message → SimMessage to every other agent (broadcast protocol)

Submission tool:
  submit_result     → stores answer in _state["submission"], terminal

Protocol support
----------------
  "msg"       — send_message, receive_messages, wait, submit_result
  "broadcast" — broadcast_message, receive_messages, list_agents, wait, submit_result
  "sfs"       — raises NotImplementedError (shared-kv layer, future milestone)

Token tracking
--------------
  The LLMFn interface returns a content string only.  If you need accurate
  output-token counts (for the C metric), wrap your llm_fn with
  make_counting_openai_fn() from adapters.py, which stores token counts in
  a shared counter dict that you pass to SiloBenchAgent.token_counter.
  If token_counter is None, output tokens are estimated as word count.

GNN state keys
--------------
  After every decide() call the agent writes the following keys into its
  .state dict so that AgentStateExtractor can assemble a GNNAgentState
  tensor for the GNNEdgeMaskRouter:

  ``"gnn_solution_embed"``   list[float] of length embed_dim_sol
  ``"gnn_uncertainty"``      float ∈ [0, 1]  (0 = certain / submitted)
  ``"gnn_inbound_embed"``    list[float] of length embed_dim_ctx
  ``"gnn_staleness"``        int  rounds since last non-empty inbox
  ``"gnn_tokens"``           float  cumulative output-token count
  ``"gnn_prev_out_degree"``  float  messages sent in the *previous* round

  By default, text embeddings are produced by a lightweight deterministic
  hash function that requires no external model.  Pass a custom ``embed_fn``
  (signature: ``(text: str) -> list[float]``) to use a real embedding model
  instead.  The agent pads or truncates the returned vector to the configured
  dimension automatically.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any, Callable

from silo_sim.agent import SimMessage
from silo_sim.utils.parsing import parse_tool_calls

LLMFn = Callable[[list[dict[str, str]]], str]
EmbedFn = Callable[[str], list[float]]

# Tools that immediately end the agent's turn for this round.
_TERMINAL_TOOLS = {"wait", "submit_result"}


def _hash_embed(text: str, dim: int) -> list[float]:
    """Deterministic text → float vector via MD5 chunking.

    Produces a reproducible, bounded vector in [-0.5, 0.5]^dim that
    captures text identity (same text → same vector) without any ML
    model.  Useful as a zero-dependency default; swap for a real
    embedding model via the ``embed_fn`` parameter when signal quality
    matters.
    """
    if not text:
        return [0.0] * dim
    out = []
    for i in range(dim):
        raw = hashlib.md5(f"{i}:{text}".encode()).hexdigest()
        out.append(int(raw, 16) % 10000 / 10000.0 - 0.5)
    return out


@dataclass
class SiloBenchAgent:
    """SILO-BENCH agent that satisfies the BaseAgent protocol.

    Parameters
    ----------
    agent_id:
        Unique integer identifier, must match Network topology key.
    llm_fn:
        Callable(messages: list[dict]) -> str — same interface as LLMAgent.
    protocol:
        "msg" | "broadcast".  ("sfs" raises NotImplementedError.)
    system_prompt:
        Generated by silo_sim.utils.prompts.generate_system_prompt().
    task_prompt:
        The per-agent task description from agent_configs[i]["user_prompt"].
    num_agents:
        Total agent count; used by list_agents and broadcast.
    token_counter:
        Optional callable(raw_response: str) -> int that returns output token
        count for the C metric.  If None, word count is used as a proxy.
    embed_dim_sol:
        Dimension of the ``gnn_solution_embed`` vector.  Must match ``d_sol``
        passed to ``make_gnn_topology_hook()``.  Default 16.
    embed_dim_ctx:
        Dimension of the ``gnn_inbound_embed`` vector.  Must match ``d_ctx``
        passed to ``make_gnn_topology_hook()``.  Default 16.
    embed_fn:
        Optional ``(text: str) -> list[float]`` embedding function.  When
        provided it is used for both solution and context embeddings; the
        returned vector is padded or truncated to the respective dim.  When
        None, a deterministic hash-based encoder is used.
    """

    agent_id: int
    llm_fn: LLMFn
    protocol: str
    system_prompt: str
    task_prompt: str
    num_agents: int
    token_counter: Callable[[str], int] | None = None

    # GNN embedding config
    embed_dim_sol: int = 16
    embed_dim_ctx: int = 16
    embed_fn: EmbedFn | None = None

    # Internal mutable fields (not part of the constructor signature the user cares about)
    _state: dict[str, Any] = field(default_factory=dict, repr=False)
    _inbox: list[SimMessage] = field(default_factory=list, repr=False)
    _history: list[dict[str, str]] = field(default_factory=list, repr=False)
    _submitted: bool = field(default=False, repr=False)
    _round: int = field(default=0, repr=False)
    _output_tokens: int = field(default=0, repr=False)
    _messages_sent: int = field(default=0, repr=False)

    # GNN feature tracking
    _staleness: int = field(default=0, repr=False)
    _prev_round_out_degree: int = field(default=0, repr=False)
    _last_response: str = field(default="", repr=False)
    # inbox text captured in observe(), before decide() clears _inbox
    _current_inbox_text: str = field(default="", repr=False)
    _inbox_was_nonempty: bool = field(default=False, repr=False)

    # Routing (set each round by silo_sim.routing.RoutingController).
    # allowed_targets=None means unrestricted; enforce=True bounces sends to
    # other agents with an error instead of letting the network drop them silently.
    allowed_targets: set[int] | None = field(default=None, repr=False)
    enforce: bool = field(default=False, repr=False)
    routing_note: str = field(default="", repr=False)

    # Knowledge + routing telemetry
    _known: set[int] = field(default_factory=set, repr=False)
    _bounced: int = field(default=0, repr=False)
    _sends_routed: int = field(default=0, repr=False)     # sends made while a routing set existed
    _sends_on_route: int = field(default=0, repr=False)   # ...of which went to an allowed target
    _route_offered: int = field(default=0, repr=False)    # allowed targets offered, summed over active rounds
    _route_used: int = field(default=0, repr=False)       # ...of which were actually messaged
    _rejected: dict[str, Any] | None = field(default=None, repr=False)  # submission a verifier reopened

    def __post_init__(self) -> None:
        self._known = {self.agent_id}
        self._state["known"] = [self.agent_id]

    # ------------------------------------------------------------------
    # BaseAgent protocol
    # ------------------------------------------------------------------

    def observe(self, messages: list[SimMessage]) -> None:
        """Called by Simulator at the start of each round."""
        self._inbox = list(messages)
        # Capture inbox features now; decide() clears _inbox before
        # _update_gnn_state() runs.
        self._inbox_was_nonempty = bool(messages)
        self._current_inbox_text = " ".join(str(m.content) for m in messages)
        if not self._submitted:  # submitted agents are inert and receive nothing (paper A.5)
            for m in messages:
                self._known |= m.known | {m.sender_id}
            self._state["known"] = sorted(self._known)

    def decide(self) -> list[SimMessage]:
        """Ask the LLM what to do and return outbound SimMessages."""
        if self._submitted:
            self._inbox = []
            self._state["sent_to"] = []
            self._update_gnn_state(outbound_count=0)
            return []

        if self.protocol == "sfs":
            raise NotImplementedError(
                "sfs protocol requires a shared key-value store; "
                "implement SfsStore and pass it to SiloBenchAgent."
            )

        if self.routing_note:
            self._history.append({"role": "user", "content": self.routing_note})

        prompt = self._build_prompt()
        raw = self.llm_fn(prompt)
        self._last_response = raw

        # Track output tokens
        counter = self.token_counter or (lambda r: len(r.split()))
        self._output_tokens += counter(raw)

        tool_calls = parse_tool_calls(raw)
        outbound, tool_results = self._dispatch(tool_calls)

        self._state["sent_to"] = [m.recipient_id for m in outbound]
        if self.allowed_targets is not None:
            self._route_offered += len(self.allowed_targets)
            self._route_used += len({m.recipient_id for m in outbound} & self.allowed_targets)

        # Append this turn to conversation history
        self._history.append({"role": "assistant", "content": raw})
        if tool_results:
            result_lines = []
            for tc, res in tool_results:
                result_lines.append(
                    f"[{tc.tool}] → {json.dumps(res, ensure_ascii=False)}"
                )
            self._history.append(
                {"role": "user", "content": "\n".join(result_lines)}
            )

        self._inbox = []
        self._round += 1

        # Refresh GNN features for the topology hook at the top of next round
        self._update_gnn_state(outbound_count=len(outbound))

        return outbound

    @property
    def state(self) -> dict[str, Any]:
        return self._state

    # ------------------------------------------------------------------
    # GNN features
    # ------------------------------------------------------------------

    def _embed(self, text: str, dim: int) -> list[float]:
        """Embed *text* into a float vector of exactly *dim* elements.

        Uses the custom embed_fn if provided, otherwise the deterministic
        hash encoder.  Always pads or truncates to exactly *dim* floats.
        """
        if self.embed_fn is not None:
            raw = list(self.embed_fn(text))
        else:
            raw = _hash_embed(text, dim)
        if len(raw) < dim:
            raw = raw + [0.0] * (dim - len(raw))
        return raw[:dim]

    def _update_gnn_state(self, outbound_count: int) -> None:
        """Write GNN routing features into self._state after each decide().

        Called at the end of every decide() turn so that AgentStateExtractor
        always sees an up-to-date snapshot when the topology hook fires at
        the top of the next round.

        Features written
        ----------------
        gnn_solution_embed  : Embedding of the agent's current best answer
                              (submission text when submitted, otherwise the
                              most recent LLM response).
        gnn_uncertainty     : 0.0 when submitted; otherwise an inverse-progress
                              heuristic that shrinks as conversation grows.
        gnn_inbound_embed   : Embedding of this round's inbox (captured before
                              the inbox was cleared).  Zeros if inbox was empty.
        gnn_staleness       : Rounds elapsed since last non-empty inbox.
        gnn_tokens          : Cumulative output-token count.
        gnn_prev_out_degree : Out-degree from the *previous* round.
        """
        # Solution embedding
        if self._submitted and self._state.get("submission"):
            solution_text = str(self._state["submission"].get("answer", ""))
        else:
            solution_text = self._last_response
        self._state["gnn_solution_embed"] = self._embed(solution_text, self.embed_dim_sol)

        # Uncertainty
        if self._submitted:
            uncertainty = 0.0
        else:
            # Each turn adds an assistant + tool-result entry to _history;
            # uncertainty decays with turns, floored at 0.1.
            turns = len(self._history) // 2
            uncertainty = max(0.1, 1.0 / (1.0 + 0.5 * turns))
        self._state["gnn_uncertainty"] = uncertainty

        # Inbound context embedding + staleness
        if self._inbox_was_nonempty:
            self._state["gnn_inbound_embed"] = self._embed(
                self._current_inbox_text, self.embed_dim_ctx
            )
            self._staleness = 0
        else:
            if "gnn_inbound_embed" not in self._state:
                self._state["gnn_inbound_embed"] = [0.0] * self.embed_dim_ctx
            self._staleness += 1
        self._state["gnn_staleness"] = self._staleness

        # Token count
        self._state["gnn_tokens"] = float(self._output_tokens)

        # Out-degree: publish last round's, then remember this round's
        self._state["gnn_prev_out_degree"] = float(self._prev_round_out_degree)
        self._prev_round_out_degree = outbound_count

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_prompt(self) -> list[dict[str, str]]:
        """Assemble the full conversation for this LLM call."""
        msgs: list[dict[str, str]] = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": self.task_prompt},
        ]
        msgs.extend(self._history)
        return msgs

    def _dispatch(
        self, tool_calls
    ) -> tuple[list[SimMessage], list[tuple]]:
        """Execute each tool call; return (outbound_msgs, (tc, result) pairs)."""
        outbound: list[SimMessage] = []
        results: list[tuple] = []

        for tc in tool_calls:
            name = tc.tool

            if name == "send_message":
                try:
                    target_id = int(tc.parameters.get("target_id", -1))
                except (TypeError, ValueError):
                    target_id = -1
                content = tc.parameters.get("content", "")
                if self.allowed_targets is not None:
                    self._sends_routed += 1
                    self._sends_on_route += target_id in self.allowed_targets
                if self.enforce and self.allowed_targets is not None and target_id not in self.allowed_targets:
                    self._bounced += 1
                    res = {
                        "success": False,
                        "error": f"Agent {target_id} is not reachable this round. "
                                 f"Reachable: {sorted(self.allowed_targets)}",
                    }
                else:
                    outbound.append(
                        SimMessage(
                            sender_id=self.agent_id,
                            recipient_id=target_id,
                            content=content,
                            sent_at=self._round,
                            known=frozenset(self._known),
                        )
                    )
                    self._messages_sent += 1
                    res = {"success": True, "message": f"Sent to agent {target_id}"}

            elif name == "broadcast_message":
                content = tc.parameters.get("content", "")
                recipients = [aid for aid in range(self.num_agents) if aid != self.agent_id]
                if self.enforce and self.allowed_targets is not None:
                    recipients = [aid for aid in recipients if aid in self.allowed_targets]
                for aid in recipients:
                    outbound.append(
                        SimMessage(
                            sender_id=self.agent_id,
                            recipient_id=aid,
                            content=content,
                            sent_at=self._round,
                            known=frozenset(self._known),
                        )
                    )
                    self._messages_sent += 1
                res = {"success": True, "message": (
                    f"Broadcast to agents {recipients}" if self.enforce and self.allowed_targets is not None
                    else "Broadcast to all agents"
                )}

            elif name == "receive_messages":
                msgs = [
                    {
                        "from": m.sender_id,
                        "content": m.content,
                        "timestamp": m.sent_at,
                    }
                    for m in self._inbox
                ]
                res = {"messages": msgs}

            elif name == "list_agents":
                res = {
                    "agent_ids": list(range(self.num_agents)),
                    "total": self.num_agents,
                }

            elif name == "wait":
                res = {"status": "waiting"}
                results.append((tc, res))
                break  # terminal

            elif name == "submit_result":
                answer = tc.parameters.get("answer")
                self._state["submission"] = {
                    "agent_id": self.agent_id,
                    "answer": answer,
                }
                self._state["known_at_submit"] = len(self._known)
                self._submitted = True
                res = {"status": "submitted"}
                results.append((tc, res))
                break  # terminal

            else:
                # Unknown tool — record error and skip
                res = {"error": f"unknown tool '{name}'"}

            results.append((tc, res))

        return outbound, results

    # ------------------------------------------------------------------
    # Convenience accessors
    # ------------------------------------------------------------------

    def notify(self, text: str) -> None:
        """Append an out-of-band note (e.g. verifier feedback) to this agent's context."""
        self._history.append({"role": "user", "content": text})

    def reopen(self) -> None:
        """Undo a submission so the agent acts and receives messages again.

        The rejected submission is kept; restore_rejected() puts it back if the
        agent never resubmits.
        """
        self._submitted = False
        self._rejected = {k: self._state.pop(k) for k in ("submission", "known_at_submit") if k in self._state}

    def restore_rejected(self) -> bool:
        """Re-submit the last rejected answer if the agent has not resubmitted. True if restored."""
        if self._submitted or not self._rejected:
            return False
        self._state.update(self._rejected)
        self._submitted = True
        return True

    @property
    def submitted(self) -> bool:
        return self._submitted

    @property
    def submission(self) -> dict[str, Any] | None:
        return self._state.get("submission")

    def reset(self) -> None:
        """Reset agent to initial state (useful for re-running the same case)."""
        self._state = {}
        self._inbox = []
        self._history = []
        self._submitted = False
        self._round = 0
        self._output_tokens = 0
        self._messages_sent = 0
        self._staleness = 0
        self._prev_round_out_degree = 0
        self._last_response = ""
        self._current_inbox_text = ""
        self._inbox_was_nonempty = False
        self._bounced = self._sends_routed = self._sends_on_route = 0
        self._route_offered = self._route_used = 0
        self._rejected = None
        self.__post_init__()
